### ISSUE TITLE
HEAD Fails to compile

### ISSUE THREAD

**Issue by apolishch** [facebook/idb#476]
```
Last 15 lines from /Users/distiller/Library/Logs/Homebrew/fbsimctl/01.build.sh:
CompileSwift normal x86_64 /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Relay.swift
    cd /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl
    /Applications/Xcode-9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CLIBootstrapper.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Arguments.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/ParserDescription.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Environment.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/DeviceReporter.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Subjects.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/iOSReporter.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/SimulatorRunners.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/JSON.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/iOSRunner.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/EventReporter.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/SimulatorReporter.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Events.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Help.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/DeviceRunners.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Parser.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Bridging.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CLI.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Runners.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Command.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/HttpRelay.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/ActionPerformer.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/AbstractTypes.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/SignalHandler.swift -primary-file /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Relay.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CommandRunners.swift -target x86_64-apple-macosx10.10 -enable-objc-interop -sdk /Applications/Xcode-9.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -I /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Products/Debug -F /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Products/Debug -F /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/Carthage/Build/Mac -enable-testing -g -import-underlying-module -module-cache-path /tmp/fbsimctl-20180402-6930-n8wt77/build/ModuleCache -swift-version 3 -enforce-exclusivity=checked -serialize-debugging-options -report-errors-to-debugger -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/swift-overrides.hmap -Xcc -iquote -Xcc /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/FBSimulatorControlKit-generated-files.hmap -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/FBSimulatorControlKit-own-target-headers.hmap -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/FBSimulatorControlKit-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/all-product-headers.yaml -Xcc -iquote -Xcc /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/FBSimulatorControlKit-project-headers.hmap -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Products/Debug/include -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/PrivateHeaders -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/DerivedSources/x86_64 -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -ivfsoverlay -Xcc /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/unextended-module-overlay.yaml -Xcc -working-directory/tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl -emit-module-doc-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/Relay~partial.swiftdoc -serialize-diagnostics-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/Relay.dia -Onone -module-name FBSimulatorControlKit -emit-module-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/Relay~partial.swiftmodule -emit-dependencies-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/Relay.d -emit-reference-dependencies-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/Relay.swiftdeps -o /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/Relay.o -index-store-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Index/DataStore -index-system-modules

CompileSwift normal x86_64 /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CommandRunners.swift
    cd /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl
    /Applications/Xcode-9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CLIBootstrapper.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Arguments.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/ParserDescription.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Environment.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/DeviceReporter.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Subjects.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/iOSReporter.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/SimulatorRunners.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/JSON.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/iOSRunner.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/EventReporter.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/SimulatorReporter.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Events.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Help.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/DeviceRunners.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Parser.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Bridging.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CLI.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Runners.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Command.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/HttpRelay.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/ActionPerformer.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/AbstractTypes.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/SignalHandler.swift /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/Relay.swift -primary-file /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CommandRunners.swift -target x86_64-apple-macosx10.10 -enable-objc-interop -sdk /Applications/Xcode-9.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -I /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Products/Debug -F /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Products/Debug -F /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/Carthage/Build/Mac -enable-testing -g -import-underlying-module -module-cache-path /tmp/fbsimctl-20180402-6930-n8wt77/build/ModuleCache -swift-version 3 -enforce-exclusivity=checked -serialize-debugging-options -report-errors-to-debugger -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/swift-overrides.hmap -Xcc -iquote -Xcc /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/FBSimulatorControlKit-generated-files.hmap -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/FBSimulatorControlKit-own-target-headers.hmap -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/FBSimulatorControlKit-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/all-product-headers.yaml -Xcc -iquote -Xcc /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/FBSimulatorControlKit-project-headers.hmap -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Products/Debug/include -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/PrivateHeaders -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/DerivedSources/x86_64 -Xcc -I/tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -ivfsoverlay -Xcc /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/unextended-module-overlay.yaml -Xcc -working-directory/tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl -emit-module-doc-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/CommandRunners~partial.swiftdoc -serialize-diagnostics-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/CommandRunners.dia -Onone -module-name FBSimulatorControlKit -emit-module-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/CommandRunners~partial.swiftmodule -emit-dependencies-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/CommandRunners.d -emit-reference-dependencies-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/CommandRunners.swiftdeps -o /tmp/fbsimctl-20180402-6930-n8wt77/build/Build/Intermediates.noindex/fbsimctl.build/Debug/FBSimulatorControlKit.build/Objects-normal/x86_64/CommandRunners.o -index-store-path /tmp/fbsimctl-20180402-6930-n8wt77/build/Index/DataStore -index-system-modules

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /tmp/fbsimctl-20180402-6930-n8wt77/fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/facebook/homebrew-fb/issues

/usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x00000101ae52c0> (NoMethodError)
Did you mean?  check_for_tap_ruby_files_locations
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

brew install fbsimctl --HEAD returned exit code 1

Action failed: brew install fbsimctl --HEAD

```

On an aside, are there any plans to version this tool?

**Comment by camillake** [comment]
same here

**Comment by dodikk** [comment]
Building from source has failed for me as well

```
❌  /Users/adodatko/projects/research/reactnative/FBSimulatorControl/fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift:1023:15: closure tuple parameter '(String, [String])' does not support destructuring

      .fmap { bundleID, fileNames in
              ^
```

```
$ xcodebuild -version
Xcode 9.3
Build version 9E145
```

**Comment by dodikk** [comment]
Seems to compile for me now https://github.com/facebook/FBSimulatorControl/pull/477

**Comment by apolishch** [comment]
Yeah I'm just gonna not. Unless the team decides to implement versioning, this is just more instability, and for a longer period of time, than I am happy to accept.

Glad it's compiling now though!

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen

**Comment by lawrencelomax** [comment]
This should have been fixed a while back
