### ISSUE TITLE
"Failed to spawn daemon" exception thrown when attempting list-targets

### ISSUE THREAD

**Issue by LeoNatan** [facebook/idb#522]
We use GitHub Issues for bugs.

--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

When running `idb list-targets`, I get the following exception:

```
➜  ~ idb list-targets
2019-05-14 14:07:35,036 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/idb/client/daemon_spawner.py", line 45, in _read_daemon_output
    json.loads(line.decode())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/idb/cli/main.py", line 189, in gen_main
    await root_command.run(args, argparse.Namespace())
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 93, in run
    return await self._get_subcommand_for_args(args).run(args, context)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 125, in run
    await self._run_impl(args)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 166, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/list_targets.py", line 25, in run_with_client
    targets = await client.list_targets()
  File "/usr/local/lib/python3.7/site-packages/idb/common/logging.py", line 109, in _async_wrapper
    raise self.translate_exception(ex)
  File "/usr/local/lib/python3.7/site-packages/idb/common/logging.py", line 84, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/idb/grpc/ipc_loader.py", line 115, in _tramp
    client = await _make_client()
  File "/usr/local/lib/python3.7/site-packages/idb/grpc/ipc_loader.py", line 101, in _make_client
    client = await daemon_provider()
  File "/usr/local/lib/python3.7/site-packages/idb/grpc/client.py", line 47, in provide_client
    force_kill=self.force_kill_daemon
  File "/usr/local/lib/python3.7/site-packages/idb/client/daemon_spawner.py", line 37, in start_daemon_if_needed
    await self._spawn_daemon()
  File "/usr/local/lib/python3.7/site-packages/idb/client/daemon_spawner.py", line 64, in _spawn_daemon
    await self._read_daemon_output(none_throws(process.stdout))
  File "/usr/local/lib/python3.7/site-packages/idb/client/daemon_spawner.py", line 47, in _read_daemon_output
    raise DaemonSpawnerException(f"Failed to spawn daemon: {line}") from e
idb.client.daemon_spawner.DaemonSpawnerException: Failed to spawn daemon: b''
```

Both the companion and client are installed. 

### Reproduction

Simply ran `idb list-targets` after installing.

### Solution

[OPTIONAL: Do you know what needs to be done to address this issue? Ideally, provide a pull request which fixes this issue.]

### Additional Information

* `idb` revision: (Not sure how to query, but latest at the time of posting the issue)

**Comment by zeyadsalloum** [comment]
are you running on mac or linux?
can you try running `idb daemon` and/or `idb daemon --notifier-path idb_companion` manually and see if that works for you?
the second is what basically runs in the background when you start idb for the first time

**Comment by LeoNatan** [comment]
Mac, sorry. Wasn't aware this runs on Linux.

The `daemon` command seems to work:

```
idb daemon
{"ipv4_grpc_port": 9889, "ipv6_grpc_port": 9889}
Running server until ^C
^C
Stopping server
```

**Comment by LeoNatan** [comment]
If I run the daemon and try `list-targets`, I get the following response:

```
idb list-targets
No available targets
```

**Comment by zeyadsalloum** [comment]
no it should work on both. buth passing --notifier-path only works on mac.
ok as a work around you can spawn the daemon yourself with `idb daemon --notifier-path idb_companion` while we figure out why the autospawning failed you

**Comment by zeyadsalloum** [comment]
yes that's expected. if you don't pass --notifier-path to the daemon. the daemon will only be aware of targets you connect to explicitly. if you pass --notifier-path it will be aware of all targets on your mac.

**Comment by LeoNatan** [comment]
I think I found something. Brew failed to link `idb-companion` because `fbsimctl` was installed.

**Comment by LeoNatan** [comment]
Yes, that solved it. I will update the question with the solution. Docs should probably be updated too.

Brew link fails because the same frameworks are shared between the companion and idb.

**Comment by LeoNatan** [comment]
Not sure if uninstalling is the right way right now, as people may want to have both installed while testing idb.

**Comment by justoneliu** [comment]
I try `brew uninstall fbsimctl` and `brew reinstall idb-companion`, then solved it.

**Comment by VatsalDev** [comment]
Facing the issue while spawning the companion.
Is there a work around to solve this issue?
As I am not able to run the below command:
- idb list-apps --udid <UDID of the booted device>

Below is the error which I am facing:
[ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/client/grpc.py", line 758, in get_stub
    target_udid=self.target_udid
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/common/direct_companion_manager.py", line 98, in get_companion_info
    f"Couldn't find companion for target with udid {target_udid}"
idb.common.types.IdbException: Couldn't find companion for target with udid 0B494FF5-80E7-4927-8FBC-B2DFE05C65CA

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/cli/main.py", line 215, in gen_main
    await root_command.run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/common/command.py", line 87, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/cli/commands/base.py", line 49, in run
    await self._run_impl(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/cli/commands/base.py", line 79, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/cli/commands/list_apps.py", line 27, in run_with_client
    apps = await client.list_apps()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/common/logging.py", line 113, in _async_wrapper
    raise self.translate_exception(ex)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/common/logging.py", line 88, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/client/grpc.py", line 157, in func_wrapper
    return await func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/client/grpc.py", line 812, in list_apps
    async with self.get_stub() as stub:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/client/grpc.py", line 763, in get_stub
    target_udid=none_throws(self.target_udid)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/client/grpc.py", line 785, in spawn_companion
    port = await companion_spawner.spawn_companion(target_udid=target_udid)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/common/companion_spawner.py", line 76, in spawn_companion
    raise CompanionSpawnerException("failed to spawn companion")
idb.common.companion_spawner.CompanionSpawnerException: failed to spawn companion
