### ISSUE TITLE
can't screenshot in real device

### ISSUE THREAD

**Issue by flasco** [facebook/idb#531]
### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]

what you did:  run `idb screenshot --udid xxx ./test.png`

expected to happen: get picture file called 'test.png'

actually happens: in busy. I press `cmd + c` and console print some tips.

```bash
^CTraceback (most recent call last):
  File "/Users/mc/anaconda3/bin/idb", line 10, in <module>
    sys.exit(main())
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/cli/main.py", line 225, in main
    return loop.run_until_complete(gen_main(cmd_input))
  File "/Users/mc/anaconda3/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/Users/mc/anaconda3/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/Users/mc/anaconda3/lib/python3.6/asyncio/base_events.py", line 1395, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/mc/anaconda3/lib/python3.6/selectors.py", line 577, in select
    kev_list = self._kqueue.control(None, max_ev, timeout)
KeyboardInterrupt
2019-06-04 14:01:30,911 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/Users/mc/anaconda3/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/grpclib/client.py", line 264, in recv_initial_metadata
    headers = await self._stream.recv_headers()
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/grpclib/protocol.py", line 226, in recv_headers
    return await self.__headers__.get()
  File "/Users/mc/anaconda3/lib/python3.6/asyncio/queues.py", line 169, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/Users/mc/anaconda3/lib/python3.6/asyncio/base_events.py", line 574, in call_soon
    self._check_closed()
  File "/Users/mc/anaconda3/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/cli/main.py", line 189, in gen_main
    await root_command.run(args, argparse.Namespace())
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/cli/commands/base.py", line 93, in run
    return await self._get_subcommand_for_args(args).run(args, context)
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/cli/commands/base.py", line 125, in run
    await self._run_impl(args)
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/cli/commands/base.py", line 166, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/cli/commands/screenshot.py", line 32, in run_with_client
    screenshot = await client.screenshot()
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/common/logging.py", line 109, in _async_wrapper
    raise self.translate_exception(ex)
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/common/logging.py", line 84, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/grpc/ipc_loader.py", line 116, in _tramp
    return await call(client, *args, **kwargs)
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/idb/ipc/screenshot.py", line 10, in client
    response = await client.stub.screenshot(ScreenshotRequest())
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/grpclib/client.py", line 598, in __call__
    return await stream.recv_message()
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/grpclib/client.py", line 329, in recv_message
    await self.recv_initial_metadata()
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/grpclib/client.py", line 286, in recv_initial_metadata
    .format(content_type))
  File "/Users/mc/anaconda3/lib/python3.6/site-packages/grpclib/utils.py", line 50, in __exit__
    assert task
AssertionError
```

what's wrong..?

I use `idb list-apps --udid xxx`, is effective.

### Reproduction

[FILL THIS OUT: How can we reproduce the bug? Provide logs for the client and server.]

### Solution

[OPTIONAL: Do you know what needs to be done to address this issue? Ideally, provide a pull request which fixes this issue.]

### Additional Information

* `idb`: 0.0.6
* `idb-companion`: 1.0.6
* `xcode`: 10.1
* mac os: 10.13.6
* real device: iPhone 6 Plus, iOS version - 12.1

**Comment by flasco** [comment]
If it is my mistake, please let me know, thank you.

**Comment by c-ryan747** [comment]
cc @lawrencelomax has recently been doing some work to fix screenshotting on devices

**Comment by lawrencelomax** [comment]
@flasco the fixes should be out now. Can you confirm this is good with a companion built from master?

**Comment by flasco** [comment]
README haven't a doc to teach me how to build `idb_companion`, I don't know if my operation is correct.

------

finally, I run succeed, it need move bin and frameworks together, I think document is very important for us...

and it works. 🍺
