### ISSUE TITLE
How to use idb for an real ipad?

### ISSUE THREAD

**Issue by yongle20078** [facebook/idb#550]
### Description
I installed the idb in a mimi2, a ipad   connected to the mini2 by usb, but after run  idb list-targets , can't find the ipad udid, just 

mini2 | 9c20e5ed38743801e3f1306b3b108e49076d0c5c | Booted | device | iOS 12.1 | arm64 | No Companion Connected
mini2 | 9c20e5ed38743801e3f1306b3b108e49076d0c5c | booted | device | iOS 12.1 | arm64 | :0

after run: idb launch com.apple.mobilesafari

return 

Application Bundle Name: Safari 浏览器 | ID: com.apple.mobilesafari | Install Type system | Container (null) cannot be launched as it's not signed with a development identity

**Comment by sumanc** [comment]
Any solution for this? My iPhone X is connected but whenI run idb launch --udid 8b79c3fcc3b950dd257c164aa6318e8e0b757a84 com.apple.mobilesafari
Application Bundle Name: Safari | ID: com.apple.mobilesafari | Install Type system | Container (null) cannot be launched as it's not signed with a development identity

It seems like idb can only launch the apps that you own and signed by your dev certificate. I am able to launch any of my test apps that are there on the device.

**Comment by c-ryan747** [comment]
Hi,
Unfortunately iOS doesn't permit launching arbitrary apps on physical devices, only those signed with a developer certificate can be launched, killed or debugged

**Comment by sumanc** [comment]
All the documentation says idb launch com.apple.Maps or idb launch com.apple.mobilesafari etc.

Also, documentation doesn't specify that we need to pass --udid for all these commands.

**Comment by c-ryan747** [comment]
Thats a good point

I think that sticking with apps like `com.apple.mobilesafari` is the best choice for most examples as this will work on simulators, but there no generic app that will work on devices as well.

It is the case that you can run some idb commands without `--udid`, but this is dependant on how many devices you have connected etc

**Comment by skumar1122** [comment]
Hi @c-ryan747 
$ idb list-targets
`QA iPhone 5 | xxxxxxxx | Booted | device | iOS 12.4 | arm64 | No Companion Connected`
No companion connected ? Do i need to use connect command first ?

And I am getting error when I try to launch basic safari on real device ?\
**$ idb launch com.apple.mobilesafari**
```
2019-09-25 14:42:45,283 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/idb/client/grpc.py", line 200, in get_stub
    target_udid=self.target_udid
  File "/usr/local/lib/python3.7/site-packages/idb/common/direct_companion_manager.py", line 101, in get_companion_info
    raise IdbException("No UDID provided and couldn't find a default companion")
idb.common.types.IdbException: No UDID provided and couldn't find a default companion

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/idb/cli/main.py", line 211, in gen_main
    await root_command.run(args)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 94, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 126, in run
    await self._run_impl(args)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 157, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/launch.py", line 54, in run_with_client
    stop=signal_handler_event("launch") if args.wait_for else None,
  File "/usr/local/lib/python3.7/site-packages/idb/common/logging.py", line 110, in _async_wrapper
    raise self.translate_exception(ex)
  File "/usr/local/lib/python3.7/site-packages/idb/common/logging.py", line 85, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/idb/client/grpc.py", line 151, in func_wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/idb/client/grpc.py", line 678, in launch
    async with self.get_stub() as stub, stub.launch.open() as stream:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/lib/python3.7/site-packages/idb/client/grpc.py", line 205, in get_stub
    target_udid=none_throws(self.target_udid)
  File "/usr/local/lib/python3.7/site-packages/idb/utils/typing.py", line 11, in none_throws
    assert optional is not None, "Unexpected None"
AssertionError: Unexpected None
```

Could you please let me know if this idb is helpful fo real devices or only simulators ?

Thanks
Shiva

**Comment by vsilicon** [comment]
I have the same issue and also want to know if idb is helpful for real devices?Thanks!

**Comment by AlexandreLage** [comment]
https://stackoverflow.com/questions/72696726/flipper-desktop-failed-to-provide-certificates-error-from-flipper-desktop/74160205#74160205

I noticed my local `idb_companion` server was crashing when Flipper tried to connect to tit, and I was able to see why.  I wrote what I learned on this answer.
