### ISSUE TITLE
Launching ui test fail

### ISSUE THREAD

**Issue by bcandreas** [facebook/idb#552]
### Description

Test done with Xcode 11, and iPhone SE(iOS 12.4)

Installing test bundle with .xctestrun give me this error :
```
 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/idb/cli/main.py", line 211, in gen_main
    await root_command.run(args)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 94, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 94, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 126, in run
    await self._run_impl(args)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/base.py", line 157, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/usr/local/lib/python3.7/site-packages/idb/cli/commands/xctest.py", line 35, in run_with_client
    artifact = await client.install_xctest(args.test_bundle_path)
  File "/usr/local/lib/python3.7/site-packages/idb/common/logging.py", line 110, in _async_wrapper
    raise self.translate_exception(ex)
  File "/usr/local/lib/python3.7/site-packages/idb/common/logging.py", line 85, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/idb/client/grpc.py", line 151, in func_wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/idb/client/grpc.py", line 413, in install_xctest
    bundle=xctest, destination=InstallRequest.XCTEST
  File "/usr/local/lib/python3.7/site-packages/idb/client/grpc.py", line 465, in _install_to_destination
    stream=stream, generator=generator, logger=self.logger
  File "/usr/local/lib/python3.7/site-packages/idb/grpc/stream.py", line 35, in drain_to_stream
    async for message in generator:
  File "/usr/local/lib/python3.7/site-packages/idb/common/install.py", line 48, in _generate_xctest_chunks
    async for chunk in tar.generate_tar(xctest_paths_to_tar(path)):
  File "/usr/local/lib/python3.7/site-packages/idb/common/xctest.py", line 66, in xctest_paths_to_tar
    return extract_paths_from_xctestrun(bundle_path)
  File "/usr/local/lib/python3.7/site-packages/idb/common/xctest.py", line 51, in extract_paths_from_xctestrun
    result.append(test_dict["TestHostPath"].replace("__TESTROOT__", test_root))
KeyError: 'TestHostPath'
```
The only way it work is with .xctest file : 
But when idb-companion make the .xctestrun file it crashed because **TestHostPath** is empty so it throw 

`idb_companion[668:10401] * Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
`
When i add **TestHostPath** value no crash but the test doesn't run. So i added a breakpoint to use the .xctestrun file made with idb-companion to launch the UI test on xcodebuild with this command as its done in idb-companion :
`xcodebuild test-without-building -xctestrun /path/filemadewithidb-companion.xctestrun -destination 'id=idb-of-real-device'`

And now i got a new error : 

`Assertion Failure: testUITests.swift:20: failed: caught "NSInternalInconsistencyException", "No target application path specified via test configuration: <XCTestConfiguration: 0x282b00270>`

When i compare the .xctestrun file produced with idb-companion with the one produced with xcode for the ui test, it seems to lack some informations. 

Do you have a template of an .xctestrun file which work using idb-companion ? So i can try to find more about this issue.

Thanks

### Additional Information

* idb-companion build from source
  idb last version

**Comment by bcandreas** [comment]
I found that to make a ui test work i need to remove **UseUITargetAppProvidedByTests** and add **UITargetAppPath** inside the .xctestrun produced by idb-companion. 
Even if i specified a target for my ui test in Xcode. Do you have the same pb ? 

Thanks !
