### ISSUE TITLE
idb list-targets  got the json error

### ISSUE THREAD

**Issue by youran1024** [facebook/idb#556]
### Step
Installed brew then these two commands
brew tap facebook/fb
brew install idb-companion
pip3.7 install fb-idb

Xcode :11.0

### Description
idb list-targets
then got the error blew

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/cli/main.py", line 211, in gen_main
    await root_command.run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/cli/commands/base.py", line 94, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/cli/commands/base.py", line 126, in run
    await self._run_impl(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/cli/commands/base.py", line 157, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/cli/commands/list_targets.py", line 24, in run_with_client
    targets = await client.list_targets()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/common/logging.py", line 110, in _async_wrapper
    raise self.translate_exception(ex)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/common/logging.py", line 85, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/client/grpc.py", line 151, in func_wrapper
    return await func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/client/grpc.py", line 831, in list_targets
    local_targets = self.local_targets_manager.get_local_targets()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/common/local_targets_manager.py", line 27, in get_local_targets
    self.local_targets = self._load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idb/common/local_targets_manager.py", line 34, in _load
    targets_list = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Solution

I have no idea

**Comment by fleytman** [comment]
similar problem

**Comment by timoteo47** [comment]
Arg ... doesn't anyone Facebook working on idb run beta code from Apple?

**Comment by timoteo47** [comment]
idb_companion crashes and generates an error message. idb_companion creates an empty /tmp/idb_local_targets file. idb checks to see if /tmp/idb_local_targets exits, then opens the file. Then it tries to load the file using json.loads which throws an error because the file is empty.

/tmp/idb_logs/notifier

Error message from /tmp/

```
2019-09-27 14:58:33.189-0700 Completed Pool Preconditons
2019-09-27 14:58:33.235 idb_companion[19108:601320] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (FBiOSTargetStateUpdate)'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff4dee32fd __exceptionPreprocess + 256
        1   libobjc.A.dylib                     0x00007fff785b8a17 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff4dee312f +[NSException raise:format:] + 201
        3   Foundation                          0x00007fff500b3a1d _writeJSONValue + 722
        4   Foundation                          0x00007fff500b416c ___writeJSONObject_block_invoke + 176
        5   CoreFoundation                      0x00007fff4de595e4 -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 161
        6   Foundation                          0x00007fff500b3bea _writeJSONObject + 454
        7   Foundation                          0x00007fff500b4fe5 ___writeJSONArray_block_invoke + 145
        8   CoreFoundation                      0x00007fff4de7b00b -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 219
        9   Foundation                          0x00007fff500b4e9c _writeJSONArray + 300
        10  Foundation                          0x00007fff500b36f7 -[_NSJSONWriter dataWithRootObject:options:error:] + 124
        11  Foundation                          0x00007fff500b35dc +[NSJSONSerialization dataWithJSONObject:options:error:] + 338
        12  idb_companion                       0x0000000107fa3e12 -[FBiOSTargetStateChangeNotifier writeTargets] + 690
        13  idb_companion                       0x0000000107fa3b36 -[FBiOSTargetStateChangeNotifier reportInitialState] + 1814
        14  idb_companion                       0x0000000107fa32f1 -[FBiOSTargetStateChangeNotifier startNotifier] + 993
        15  idb_companion                       0x0000000107fac213 GetCompanionCompletedFuture + 1731
        16  idb_companion                       0x0000000107fab66f main + 751
        17  libdyld.dylib                       0x00007fff79d863d5 start + 1
        18  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

```

**Comment by JanithaR** [comment]
Is there a workaround to this? or should we wait for some kinda solution from the devs?

**Comment by peileenf** [comment]
I met the same problem, any solution for this issue?

**Comment by t-benze** [comment]
I encountered this issue after connecting my physical device. Resolved after "Trust the device"
