### ISSUE TITLE
install idb from tarball failed with "Exception: error: ['grpc_tools.protoc'..."

### ISSUE THREAD

**Issue by guyingzhao** [facebook/idb#589]
### Description and Reproduction

we have a private pypi server and distribute fb-idb as tarball  fb-idb-*.tar.gz.

install idb from tarball in a newly setup macOS with:

```shell
pip3 install fb-idb -i http://xxx.xxx.xxx.xxx/simple --trusted-host xxx.xxx.xxx.xxx
```
error message:

```shell
    protoc-gen-python_grpc: program not found or is not executable
    Please specify a program using absolute path or make sure the program is available in your PATH system variable
    --python_grpc_out: protoc-gen-python_grpc: Plugin failed with status code 1.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/81/h_vxlgmx50s9t8yfgw394twm0000gp/T/pip-install-zz01ecw4/fb-idb/setup.py", line 77, in <module>
        cmdclass={"build_py": BuildPyCommand},
      File "/Users/zuosiyang/Library/Python/3.7/lib/python/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/zuosiyang/Library/Python/3.7/lib/python/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/81/h_vxlgmx50s9t8yfgw394twm0000gp/T/pip-install-zz01ecw4/fb-idb/setup.py", line 35, in run
        raise Exception("error: {} failed".format(command))
    Exception: error: ['grpc_tools.protoc', '--proto_path=/private/var/folders/81/h_vxlgmx50s9t8yfgw394twm0000gp/T/pip-install-zz01ecw4/fb-idb/proto', '--python_out=/private/var/folders/81/h_vxlgmx50s9t8yfgw394twm0000gp/T/pip-install-zz01ecw4/fb-idb/build/lib/idb/grpc', '--python_grpc_out=/private/var/folders/81/h_vxlgmx50s9t8yfgw394twm0000gp/T/pip-install-zz01ecw4/fb-idb/build/lib/idb/grpc', '/private/var/folders/81/h_vxlgmx50s9t8yfgw394twm0000gp/T/pip-install-zz01ecw4/fb-idb/proto/idb.proto'] failed
    ----------------------------------------
```

### Reason

`protoc-gen-python_grpc: program not found or is not executable`

I have made some trials and finally found the cause:

* idb `setup.py` use grpcio-tools to compile `proto/idb.proto` to python proto file
* if you specified `--python_grpc_out` option with grpcio-tools then you must have `protoc-gen-python_grpc` executable installed on your PC
* `protoc-gen-python_grpc` will not automatically be generated if you just install python library grpcio-tools or protobuf, you have to git clone grpc repo, pull submodules and then build.

### Solution

I found out that there is a `--grpc_python_out` option instead of `--python_grpc_out`, the words order means quite differently:

* `--grpc_python_out` does not require `protoc-gen-python_grpc`, and the output grpc files will have two files as suffix is "\*\_pb2_grpc.py" and "\*\_grpc.py" for protobuf2.
* `--python_grpc_out` requires `protoc-gen-python_grpc`, and the output file's suffix is "\*\_grpc.py"

![image](https://user-images.githubusercontent.com/22538408/76401632-2a6d5b00-63bd-11ea-898f-be58cfab5089.png)

Here is the solution:

* replace `--python_grpc_out` with `--grpc_python_out`
* modify the output file name from "idb\_grpc.py" to "idb\_pb2_grpc.py"

I made a try and the solution worked well.

### Additional Information

* `idb` revision: [1.0.10]

**Comment by guyingzhao** [comment]
fix by #592
