### ISSUE TITLE
Can not run the UI test

### ISSUE THREAD

**Issue by sgorillad** [facebook/idb#638]
### Description

 **I followed the instructions to build idb on a mac.Then I could not execute ui test for app.**

`idb xctest install /Users/xx/Library/Developer/Xcode/DerivedData/demo1-gwoqherwnhekmfaepkzqsdihebnk/Build/Products/Debug-iphoneos/demo1UITests-Runner.app/PlugIns/demo1UITests.xctest`
Installed: com.xx.demo1UITests DFAC3739-0233-34F4-991C-339600A4ACFC

`idb xctest run app com.xx.demo1UITests com.xx.demo`
Could not find shims in any of the expected directories [/Users/xx/Library/Developer/Xcode/DerivedData/idb_companion-ddsgwcyerlfaybaslyhfeiezsbcx/Build/Products/lib, /Users/xx/Library/Developer/Xcode/DerivedData/idb_companion-ddsgwcyerlfaybaslyhfeiezsbcx/Build/Products/bin, /Users/xx/Library/Developer/Xcode/DerivedData/idb_companion-ddsgwcyerlfaybaslyhfeiezsbcx/Build/Products/idb, /Users/xx/Library/Developer/Xcode/DerivedData/idb_companion-ddsgwcyerlfaybaslyhfeiezsbcx/Build/Products/idb/bin, /Users/xx/Library/Developer/Xcode/DerivedData/idb_companion-ddsgwcyerlfaybaslyhfeiezsbcx/Build/Products/Debug/FBDeviceControl.framework/Versions/A/Resources]

 **If I use the idb_companion installed by brew，I get it** 

2020-11-25 00:40:23.912 idb_companion[7560:76990]  Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: ' -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
 First throw call stack:
(
	0   CoreFoundation                      0x00007fff2049b6af __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201d33c9 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2054fa9a -[__NSCFString characterAtIndex:].cold.1 + 0
	3   CoreFoundation                      0x00007fff2055b87b -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5 + 0
	4   CoreFoundation                      0x00007fff203ab28a -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 235
	5   CoreFoundation                      0x00007fff203ab185 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
	6   XCTestBootstrap                     0x00000001067da154 +[FBXcodeBuildOperation xctestRunProperties:] + 692
	7   FBDeviceControl                     0x00000001065bbeac -[FBDeviceXCTestCommands createXCTestRunFileFromConfiguration:error:] + 300
	8   FBDeviceControl                     0x00000001065b99af -[FBDeviceXCTestCommands _startTestWithLaunchConfiguration:logger:] + 111
	9   FBDeviceControl                     0x00000001065b92dd __75-[FBDeviceXCTestCommands startTestWithLaunchConfiguration:reporter:logger:]_block_invoke + 77
	10  FBControlCore                       0x0000000106468e57 __25-[FBFuture onQueue:fmap:]_block_invoke + 391
	11  FBControlCore                       0x0000000106467cb4 __39-[FBFuture onQueue:notifyOfCompletion:]_block_invoke + 36
	12  libdispatch.dylib                   0x00007fff2017d5dd _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x00007fff2017e7c7 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00007fff2018ab86 _dispatch_main_queue_callback_4CF + 940
	15  CoreFoundation                      0x00007fff2045e960 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00007fff20420842 __CFRunLoopRun + 2731
	17  CoreFoundation                      0x00007fff2041f6be CFRunLoopRunSpecific + 563
	18  Foundation                          0x00007fff211a9fa1 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
	19  Foundation                          0x00007fff212337c4 -[NSRunLoop(NSRunLoop) runUntilDate:] + 103
	20  FBControlCore                       0x000000010641e5db -[NSRunLoop(FBControlCore) spinRunLoopWithTimeout:untilTrue:] + 267
	21  FBControlCore                       0x000000010641eadc -[NSRunLoop(FBControlCore) awaitCompletionOfFuture:timeout:error:] + 236
	22  FBControlCore                       0x000000010641ee7e -[FBFuture(NSRunLoop) awaitWithTimeout:error:] + 94
	23  FBControlCore                       0x000000010641ee14 -[FBFuture(NSRunLoop) await:] + 52
	24  idb_companion                       0x0000000104bc086e main + 1918
	25  libdyld.dylib                       0x00007fff20344631 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

### Reproduction
MacOS 11.0.1
idb v1.1.0
fb-idb  1.0.12
Xcode 12.2
idb-companion: 1.0.14 (by brew)

**Comment by c-ryan747** [comment]
For the shims issue you might need to set the environment variable `TEST_SHIMS_DIRECTORY` to `REPO_ROOT/Shims/Binaries`

**Comment by mwakizaka** [comment]
I'm getting the same issue. Where can I find shims directory?

- environment
MacOS: 11.4
idb: v1.1.2
fb-idb: 1.1.2
Xcode: 12.4
idb-companion: 1.1.2

- log
```
idb xctest run app --udid 59E46359-C737-479C-8798-06721373EDF6 com.facebook.wda.runner 2B1C3A78-4A11-3095-BF33-B0F58CC8258D -port 8100 --listen
2021-07-08 13:04:38,972 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/grpc/client.py", line 196, in func_wrapper_gen
    async for item in func(*args, **kwargs):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/grpc/client.py", line 982, in run_xctest
    async for response in stream:
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/grpclib/stream.py", line 61, in __anext__
    message = await self.recv_message()
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/grpclib/client.py", line 408, in recv_message
    await self.recv_initial_metadata()
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/grpclib/client.py", line 376, in recv_initial_metadata
    self._raise_for_grpc_status(headers_map)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/grpclib/client.py", line 337, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'Could not find shims in any of the expected directories [/usr/local/Homebrew/Library/Homebrew, /usr/local/lib, /usr/local/bin, /usr/local/idb, /usr/local/idb/bin, /usr/local/Cellar/idb-companion/1.1.2/Frameworks/FBControlCore.framework/Resources]', None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/grpc/management.py", line 115, in from_udid
    yield client
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 66, in _get_client
    yield client
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 128, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/commands/xctest.py", line 215, in run_with_client
    log_directory_path=args.log_directory_path,
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/common/logging.py", line 146, in _async_gen_wrapper
    raise ex
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/common/logging.py", line 121, in _async_gen_wrapper
    async for value in function(*args, **kwargs):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/grpc/client.py", line 199, in func_wrapper_gen
    raise IdbException(e.message) from e  # noqa B306
idb.common.types.IdbException: Could not find shims in any of the expected directories [/usr/local/Homebrew/Library/Homebrew, /usr/local/lib, /usr/local/bin, /usr/local/idb, /usr/local/idb/bin, /usr/local/Cellar/idb-companion/1.1.2/Frameworks/FBControlCore.framework/Resources]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/main.py", line 287, in gen_main
    await root_command.run(args)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/common/command.py", line 90, in run
    return await self.resolve_command_from_args(args).run(args)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 106, in run
    await self._run_impl(args)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 128, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 188, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 66, in _get_client
    yield client
  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 189, in __aexit__
    raise RuntimeError("generator didn't stop after athrow()")
RuntimeError: generator didn't stop after athrow()
2021-07-08 13:04:38,981 [ERROR] - asyncio - Task was destroyed but it is pending!
task: <Task pending coro=<<async_generator_athrow without __name__>()>>
```
