### ISSUE TITLE
Running  idb ui describe-all  causes:  ('Connection lost',)

### ISSUE THREAD

**Issue by tkirby** [facebook/idb#652]
### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]

1 Installed idb via instructions on this site.
2 Connected to simulator on my MacBook Air.
3 Ran some comments to test the idb app and all worked as expected.
4 Tried to run 'idb ui describe-all' and idb ui describe-point 100 100' to see  what is displayed. Both commands caused the following error:

('Connection lost',)

Is there some other component I need to install to make this work?

Further commands after that resulted in a python stack trace.

[ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/idb/grpc/client.py", line 156, in func_wrapper
    return await func(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/idb/grpc/client.py", line 291, in accessibility_info
    response = await self.stub.accessibility_info(
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 850, in __call__
    await stream.send_message(message, end=True)
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 241, in send_message
    await self.send_request()
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 173, in send_request
    protocol = await self._channel.__connect__()
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 696, in __connect__
    self._protocol = await self._create_connection()
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 679, in _create_connection
    _, protocol = await self._loop.create_connection(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1033, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 59115, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 59115)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/idb/cli/main.py", line 272, in gen_main
    await root_command.run(args)
  File "/Library/Python/3.8/site-packages/idb/common/command.py", line 87, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "/Library/Python/3.8/site-packages/idb/common/command.py", line 87, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "/Library/Python/3.8/site-packages/idb/cli/__init__.py", line 95, in run
    await self._run_impl(args)
  File "/Library/Python/3.8/site-packages/idb/cli/__init__.py", line 128, in _run_impl
    raise ex
  File "/Library/Python/3.8/site-packages/idb/cli/__init__.py", line 117, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/Library/Python/3.8/site-packages/idb/cli/commands/accessibility.py", line 42, in run_with_client
    info = await client.accessibility_info(point=(args.x, args.y))
  File "/Library/Python/3.8/site-packages/idb/common/logging.py", line 107, in _async_wrapper
    raise ex
  File "/Library/Python/3.8/site-packages/idb/common/logging.py", line 82, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/idb/grpc/client.py", line 162, in func_wrapper
    raise IdbConnectionException(e.strerror)
idb.common.types.IdbConnectionException: None
kirby@Richards-MacBook-Air rubygems-3.2.11 % idb connect 52408B53-1D2E-459B-B623-AE071D82C9A7
udid: 52408B53-1D2E-459B-B623-AE071D82C9A7 is_local: True
kirby@Richards-MacBook-Air rubygems-3.2.11 % idb ui describe-point 100 100
('Connection lost',)
kirby@Richards-MacBook-Air rubygems-3.2.11 % idb ui describe-point 100 100
2021-02-25 23:41:40,726 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/idb/grpc/client.py", line 156, in func_wrapper
    return await func(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/idb/grpc/client.py", line 291, in accessibility_info
    response = await self.stub.accessibility_info(
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 850, in __call__
    await stream.send_message(message, end=True)
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 241, in send_message
    await self.send_request()
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 173, in send_request
    protocol = await self._channel.__connect__()
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 696, in __connect__
    self._protocol = await self._create_connection()
  File "/Library/Python/3.8/site-packages/grpclib/client.py", line 679, in _create_connection
    _, protocol = await self._loop.create_connection(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1033, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 59427, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 59427)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/idb/cli/main.py", line 272, in gen_main
    await root_command.run(args)
  File "/Library/Python/3.8/site-packages/idb/common/command.py", line 87, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "/Library/Python/3.8/site-packages/idb/common/command.py", line 87, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "/Library/Python/3.8/site-packages/idb/cli/__init__.py", line 95, in run
    await self._run_impl(args)
  File "/Library/Python/3.8/site-packages/idb/cli/__init__.py", line 128, in _run_impl
    raise ex
  File "/Library/Python/3.8/site-packages/idb/cli/__init__.py", line 117, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/Library/Python/3.8/site-packages/idb/cli/commands/accessibility.py", line 42, in run_with_client
    info = await client.accessibility_info(point=(args.x, args.y))
  File "/Library/Python/3.8/site-packages/idb/common/logging.py", line 107, in _async_wrapper
    raise ex
  File "/Library/Python/3.8/site-packages/idb/common/logging.py", line 82, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/idb/grpc/client.py", line 162, in func_wrapper
    raise IdbConnectionException(e.strerror)
idb.common.types.IdbConnectionException: None

### Reproduction

[FILL THIS OUT: How can we reproduce the bug? Provide logs for the client and server.]

### Solution

No I've just downloaded and begun testing this tool

### Additional Information

* `idb` revision:

I could not figure how to get version number.  idb -v, idb --version, idb revision, idb --help. None of these showed a version number as far as I can tell.

**Comment by nesevis** [comment]
The last release is quite stale at the moment. I had to build from source to get it to work.

**Comment by stoefln** [comment]
Same problem here
