### ISSUE TITLE
idb xctest run app failed because of Could not find shims error

### ISSUE THREAD

**Issue by mwakizaka** [facebook/idb#686]
### Description

- When I tried to launch WebDriverAgent app with xctest, it failed because `Could not find shims in any of the expected directories`.

### Reproduction

```
$ idb xctest run app --udid 59E46359-C737-479C-8798-06721373EDF6 com.facebook.wda.runner 2B1C3A78-4A11-3095-BF33-B0F58CC8258D -port 8100 --listen
2021-07-08 13:04:38,972 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/grpc/client.py", line 196, in func_wrapper_gen
    async for item in func(*args, **kwargs):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/grpc/client.py", line 982, in run_xctest
    async for response in stream:
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/grpclib/stream.py", line 61, in __anext__
    message = await self.recv_message()
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/grpclib/client.py", line 408, in recv_message
    await self.recv_initial_metadata()
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/grpclib/client.py", line 376, in recv_initial_metadata
    self._raise_for_grpc_status(headers_map)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/grpclib/client.py", line 337, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'Could not find shims in any of the expected directories [/usr/local/Homebrew/Library/Homebrew, /usr/local/lib, /usr/local/bin, /usr/local/idb, /usr/local/idb/bin, /usr/local/Cellar/idb-companion/1.1.2/Frameworks/FBControlCore.framework/Resources]', None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/grpc/management.py", line 115, in from_udid
    yield client
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 66, in _get_client
    yield client
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 128, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/commands/xctest.py", line 215, in run_with_client
    log_directory_path=args.log_directory_path,
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/common/logging.py", line 146, in _async_gen_wrapper
    raise ex
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/common/logging.py", line 121, in _async_gen_wrapper
    async for value in function(*args, **kwargs):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/grpc/client.py", line 199, in func_wrapper_gen
    raise IdbException(e.message) from e  # noqa B306
idb.common.types.IdbException: Could not find shims in any of the expected directories [/usr/local/Homebrew/Library/Homebrew, /usr/local/lib, /usr/local/bin, /usr/local/idb, /usr/local/idb/bin, /usr/local/Cellar/idb-companion/1.1.2/Frameworks/FBControlCore.framework/Resources]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/main.py", line 287, in gen_main
    await root_command.run(args)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/common/command.py", line 90, in run
    return await self.resolve_command_from_args(args).run(args)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 106, in run
    await self._run_impl(args)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 128, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 188, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/mwakizaka/.virtualenvs/idb_py/lib/python3.7/site-packages/idb/cli/__init__.py", line 66, in _get_client
    yield client
  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 189, in __aexit__
    raise RuntimeError("generator didn't stop after athrow()")
RuntimeError: generator didn't stop after athrow()
2021-07-08 13:04:38,981 [ERROR] - asyncio - Task was destroyed but it is pending!
task: <Task pending coro=<<async_generator_athrow without __name__>()>>
```

### Additional Information

- MacOS: 11.4
- idb: v1.1.2
- fb-idb: 1.1.2
- Xcode: 12.4
- idb-companion: 1.1.2

Ref: https://github.com/facebook/idb/issues/638

**Comment by jbardini** [comment]
We've just release `idb-companion 1.1.5` and `fb-idb 1.1.5` with changes on how shims are built and handled. Please update and re-check.

**Comment by mwakizaka** [comment]
Thank you so much for your help. It looks working as expected!
