### ISSUE TITLE
idb-companion failed to install on MacBook M1

### ISSUE THREAD

**Issue by ravimaurya-nickelfox** [facebook/idb#747]
We use GitHub Issues for bugs.

--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

Failed to install idb-companion on MacBook Air M1.

Following error occurred during installation

```shell
==> pod install
==> ./idb_build.sh idb_companion build /opt/homebrew/Cellar/idb-companion/1.1.5
Last 15 lines from /Users/ravikumar/Library/Logs/Homebrew/idb-companion/02.idb_build.sh:
WriteAuxiliaryFile /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/Objects-normal/arm64/idbGRPC.LinkFileList (in target 'idbGRPC' from project 'idb_companion')
    cd /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5
    write-file /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/Objects-normal/arm64/idbGRPC.LinkFileList

Libtool /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Products/Debug/BoringSSL-GRPC/libBoringSSL-GRPC.a normal (in target 'BoringSSL-GRPC' from project 'Pods')
    cd /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/Pods
    export MACOSX_DEPLOYMENT_TARGET\=10.10
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only arm64 -D -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -L/tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Products/Debug/BoringSSL-GRPC -filelist /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Intermediates.noindex/Pods.build/Debug/BoringSSL-GRPC.build/Objects-normal/arm64/BoringSSL-GRPC.LinkFileList -dependency_info /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Intermediates.noindex/Pods.build/Debug/BoringSSL-GRPC.build/Objects-normal/arm64/BoringSSL-GRPC_libtool_dependency_info.dat -o /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Products/Debug/BoringSSL-GRPC/libBoringSSL-GRPC.a

** BUILD FAILED **


The following build commands failed:
	RuleScriptExecution /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.h /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.cc /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.h /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.cc /tmp/idb-companion-20211111-41348-1o1nhf9/idb-1.1.5/proto/idb.proto normal arm64 (in target 'idbGRPC' from project 'idb_companion')
(1 failure)

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
idb-companion.rb should have branch set to main https://github.com/facebook/homebrew-fb/issues/67
```
### Reproduction

Just followed steps here https://fbidb.io/docs/installation but that doesn't seem to be working for M1

### Additional Information

Homebrew 3.3.3
Homebrew/homebrew-core (git revision c4267c371e7; last commit 2021-11-11)

**Comment by BanidAzin** [comment]
I'm experiencing the same problem

**Comment by essana3** [comment]
Same here

**Comment by Ashoat** [comment]
`brew install --HEAD idb-companion` is giving this error. Based on #649, there was only a short period around two weeks ago where idb HEAD was working for the M1 (eg. around d339206e071b7968dff798042330056281268bea)

**Comment by essana3** [comment]
> `brew install --HEAD idb-companion` is giving this error ([log](https://gist.github.com/Ashoat/8fee48e9ba0aa983fd82ef626ef16a61)). Based on #649, there was only a short period around two weeks ago where idb HEAD was working for the M1 (eg. around [d339206](https://github.com/facebook/idb/commit/d339206e071b7968dff798042330056281268bea))

I have the exact same problem

**Comment by swrobel** [comment]
With `brew install --HEAD idb-companion` on my M1 Max Macbook Pro I'm now seeing:

```
The following build commands failed:
	CompileC /tmp/idb-companion-20211125-56098-npzr7o/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/Objects-normal/arm64/FBDataConsumer.o /tmp/idb-companion-20211125-56098-npzr7o/FBControlCore/Utility/FBDataConsumer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FBControlCore' from project 'FBSimulatorControl')
(1 failure)
```

**Comment by ravimaurya-nickelfox** [comment]
Looks like FB (Meta) is not looking at this issue 😞

**Comment by rpavlovs** [comment]
Same issue is still present, mac m1

**Comment by seyaobey-dev** [comment]
Same issue here, mac m1

**Comment by n-popov-geniusee** [comment]
Have a the same issue

**Comment by mxmzb** [comment]
Failing for me, too, but with different error:

```
❯ brew install --HEAD idb-companion

==> Cloning https://github.com/facebook/idb.git
Cloning into '/Users/maxim/Library/Caches/Homebrew/idb-companion--git'...
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
==> Installing idb-companion from facebook/fb
==> pod install
==> ./idb_build.sh idb_companion build /opt/homebrew/Cellar/idb-companion/HEAD-43a3ecc
Last 15 lines from /Users/maxim/Library/Logs/Homebrew/idb-companion/02.idb_build.sh:
    cd /tmp/idb-companion-20220104-84781-moklyk
    export LANG\=en_US.US-ASCII
    clang -x objective-c -target arm64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/tmp/idb-companion-20220104-84781-moklyk/build/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/tmp/idb-companion-20220104-84781-moklyk/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=FBSimulatorControl -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Werror\=incompatible-pointer-types -Werror\=implicit-function-declaration -Wmissing-field-initializers -Wmissing-prototypes -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wunknown-pragmas -Wshadow -Wfour-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wsign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -index-store-path /tmp/idb-companion-20220104-84781-moklyk/build/Index/DataStore -iquote /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-generated-files.hmap -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-own-target-headers.hmap -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/all-product-headers.yaml -iquote /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-project-headers.hmap -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Products/Debug/include -I/tmp/idb-companion-20220104-84781-moklyk/PrivateHeaders -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources-normal/arm64 -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources/arm64 -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources -F/tmp/idb-companion-20220104-84781-moklyk/build/Build/Products/Debug -F/Applications/Xcode.app/Contents/Frameworks -F/Applications/Xcode.app/Contents/PlugIns -F/Applications/Xcode.app/Contents/OtherFrameworks -F/Applications/Xcode.app/Contents/SharedFrameworks -F/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/PrivateFrameworks -F/Library/Developer/PrivateFrameworks -MMD -MT dependencies -MF /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/arm64/FBSimulatorConfiguration.d --serialize-diagnostics /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/arm64/FBSimulatorConfiguration.dia -c /tmp/idb-companion-20220104-84781-moklyk/FBSimulatorControl/Configuration/FBSimulatorConfiguration.m -o /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/arm64/FBSimulatorConfiguration.o

CompileC /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/arm64/FBSimulatorConfiguration+CoreSimulator.o /tmp/idb-companion-20220104-84781-moklyk/FBSimulatorControl/Configuration/FBSimulatorConfiguration+CoreSimulator.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FBSimulatorControl' from project 'FBSimulatorControl')
    cd /tmp/idb-companion-20220104-84781-moklyk
    export LANG\=en_US.US-ASCII
    clang -x objective-c -target arm64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/tmp/idb-companion-20220104-84781-moklyk/build/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/tmp/idb-companion-20220104-84781-moklyk/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=FBSimulatorControl -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Werror\=incompatible-pointer-types -Werror\=implicit-function-declaration -Wmissing-field-initializers -Wmissing-prototypes -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wunknown-pragmas -Wshadow -Wfour-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wsign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -index-store-path /tmp/idb-companion-20220104-84781-moklyk/build/Index/DataStore -iquote /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-generated-files.hmap -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-own-target-headers.hmap -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/all-product-headers.yaml -iquote /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-project-headers.hmap -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Products/Debug/include -I/tmp/idb-companion-20220104-84781-moklyk/PrivateHeaders -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources-normal/arm64 -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources/arm64 -I/tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources -F/tmp/idb-companion-20220104-84781-moklyk/build/Build/Products/Debug -F/Applications/Xcode.app/Contents/Frameworks -F/Applications/Xcode.app/Contents/PlugIns -F/Applications/Xcode.app/Contents/OtherFrameworks -F/Applications/Xcode.app/Contents/SharedFrameworks -F/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/PrivateFrameworks -F/Library/Developer/PrivateFrameworks -MMD -MT dependencies -MF /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/arm64/FBSimulatorConfiguration+CoreSimulator.d --serialize-diagnostics /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/arm64/FBSimulatorConfiguration+CoreSimulator.dia -c /tmp/idb-companion-20220104-84781-moklyk/FBSimulatorControl/Configuration/FBSimulatorConfiguration+CoreSimulator.m -o /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/arm64/FBSimulatorConfiguration+CoreSimulator.o

** BUILD FAILED **


The following build commands failed:
	CompileC /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/Objects-normal/arm64/idb.pb.o /tmp/idb-companion-20220104-84781-moklyk/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'idbGRPC' from project 'idb_companion')
(1 failure)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/facebook/homebrew-fb/issues

These open issues may also help:
./idb_build.sh idb_companion build /** BUILD FAILED ** https://github.com/facebook/homebrew-fb/issues/73
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
env PATH="${PATH//$(pyenv root)\/shims:/}" brew install --HEAD idb-companion  75.70s user 56.94s system 51% cpu 4:18.34 total
```

**Comment by fungilation** [comment]
Failing too on my M1 macbook:

```
> brew install --HEAD idb-companion
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Cloning https://github.com/facebook/idb.git
Cloning into '/Users/gfung/Library/Caches/Homebrew/idb-companion--git'...
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
==> Installing idb-companion from facebook/fb
==> pod install
==> ./idb_build.sh idb_companion build /usr/local/Cellar/idb-companion/HEAD-dc0e7dc
Last 15 lines from /Users/gfung/Library/Logs/Homebrew/idb-companion/02.idb_build.sh:
In file included from /usr/local/include/google/protobuf/generated_message_bases.h:41:
/tmp/idb-companion-20220110-98631-1kxaoyy/Pods/Headers/Public/Protobuf-C++/google/protobuf/generated_message_util.h:162:22: note: candidate function not viable: no known conversion from 'idb::Payload *' to 'google::protobuf::MessageLite *' for 1st argument
PROTOBUF_EXPORT void GenericSwap(MessageLite* m1, MessageLite* m2);
                     ^
/tmp/idb-companion-20220110-98631-1kxaoyy/Pods/Headers/Public/Protobuf-C++/google/protobuf/generated_message_util.h:164:22: note: candidate function not viable: no known conversion from 'idb::Payload *' to 'google::protobuf::Message *' for 1st argument
PROTOBUF_EXPORT void GenericSwap(Message* m1, Message* m2);
                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

** BUILD FAILED **


The following build commands failed:
	CompileC /tmp/idb-companion-20220110-98631-1kxaoyy/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/Objects-normal/x86_64/idb.pb.o /tmp/idb-companion-20220110-98631-1kxaoyy/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'idbGRPC' from project 'idb_companion')
(1 failure)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/facebook/homebrew-fb/issues

These open issues may also help:
./idb_build.sh idb_companion build /** BUILD FAILED ** https://github.com/facebook/homebrew-fb/issues/73
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```

**Comment by fatih18** [comment]
failing M1 mcp 

Error: Command failed: /opt/homebrew/bin/idb list-targets --json
2022-01-19 16:56:00,130 [ERROR] - root - Exception thrown in main

Traceback (most recent call last):

  File "/opt/homebrew/lib/python3.9/site-packages/idb/cli/main.py", line 313, in gen_main

    await root_command.run(args)

  File "/opt/homebrew/lib/python3.9/site-packages/idb/common/command.py", line 90, in run

    return await self.resolve_command_from_args(args).run(args)

  File "/opt/homebrew/lib/python3.9/site-packages/idb/cli/__init__.py", line 106, in run

    await self._run_impl(args)

  File "/opt/homebrew/lib/python3.9/site-packages/idb/cli/__init__.py", line 149, in _run_impl

    await self.run_with_manager(

  File "/opt/homebrew/lib/python3.9/site-packages/idb/cli/commands/target.py", line 188, in run_with_manager

    targets = await manager.list_targets(only=only)

  File "/opt/homebrew/lib/python3.9/site-packages/idb/common/logging.py", line 113, in _async_wrapper

    raise ex

  File "/opt/homebrew/lib/python3.9/site-packages/idb/common/logging.py", line 88, in _async_wrapper

    value = await function(*args, **kwargs)

  File "/opt/homebrew/lib/python3.9/site-packages/idb/grpc/management.py", line 197, in list_targets

    (local_targets, connected_targets) = await asyncio.gather(

  File "/opt/homebrew/lib/python3.9/site-packages/idb/grpc/management.py", line 195, in _list_local_targets

    return await companion.list_targets(only=only)

  File "/opt/homebrew/lib/python3.9/site-packages/idb/common/logging.py", line 113, in _async_wrapper

    raise ex

  File "/opt/homebrew/lib/python3.9/site-packages/idb/common/logging.py", line 88, in _async_wrapper

    value = await function(*args, **kwargs)

  File "/opt/homebrew/lib/python3.9/site-packages/idb/common/companion.py", line 383, in list_targets

    output = await self._run_companion_command(arguments=arguments, timeout=timeout)

  File "/opt/homebrew/lib/python3.9/site-packages/idb/common/companion.py", line 161, in _run_companion_command

    async with self._start_companion_command(arguments=arguments) as process:

  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 181, in __aenter__

    return await self.gen.__anext__()

  File "/opt/homebrew/lib/python3.9/site-packages/idb/common/companion.py", line 137, in _start_companion_command

    process = await asyncio.create_subprocess_exec(

  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec

    transport, protocol = await loop.subprocess_exec(

  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec

    transport = await self._make_subprocess_transport(

  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport

    transp = _UnixSubprocessTransport(self, protocol, args, shell,

  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__

    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,

  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 789, in _start

    self._proc = subprocess.Popen(

  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/idb_companion'

**Comment by radiodario** [comment]
Download the latest brew bottle from here:

https://github.com/facebook/idb/releases

```
wget https://github.com/facebook/idb/releases/download/v1.1.6/idb-companion-1.1.6.monterey.bottle.tar.gz
brew install -f idb-companion-1.1.6.monterey.bottle.tar.gz
```

**Comment by jhylmb** [comment]
@radiodario thank you

your solution works with m1 macbook pro.

> Download the latest brew bottle from here:
> 
> https://github.com/facebook/idb/releases
> 
> ```
> wget https://github.com/facebook/idb/releases/download/v1.1.6/idb-companion-1.1.6.monterey.bottle.tar.gz
> brew install -f idb-companion-1.1.6.monterey.bottle.tar.gz
> ```

**Comment by jbardini** [comment]
Build on M1 has been fixed on idb-companion v1.1.7. A `arm64_monterey` bottle was also published.
