### ISSUE TITLE
Stream not working

### ISSUE THREAD

**Issue by jagdish-mozark** [facebook/idb#841]
I am using idb version fb-idb 1.1.7

while using video-stream i am not getting stream.

Command :  
`idb video-stream --fps 15 --format h264 --compression-quality 1.0 --udid  00008030-0002292E217A402E
`
Output
```
Running stream until ^C
2023-07-20 18:06:24,038 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/idb/cli/main.py", line 313, in gen_main
    await root_command.run(args)
  File "/usr/local/lib/python3.11/site-packages/idb/common/command.py", line 90, in run
    return await self.resolve_command_from_args(args).run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/idb/cli/__init__.py", line 106, in run
    await self._run_impl(args)
  File "/usr/local/lib/python3.11/site-packages/idb/cli/__init__.py", line 128, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/usr/local/lib/python3.11/site-packages/idb/cli/commands/video.py", line 88, in run_with_client
    async for data in signal_handler_generator(
  File "/usr/local/lib/python3.11/site-packages/idb/common/signal.py", line 57, in signal_handler_generator
    yield consume.result()
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/idb/grpc/client.py", line 1060, in stream_video
    async for data in iterator:
  File "/usr/local/lib/python3.11/site-packages/idb/grpc/stream.py", line 51, in generate_bytes
    async for item in stream:
  File "/usr/local/lib/python3.11/site-packages/grpclib/stream.py", line 61, in __anext__
    message = await self.recv_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpclib/client.py", line 425, in recv_message
    await self.recv_initial_metadata()
  File "/usr/local/lib/python3.11/site-packages/grpclib/client.py", line 393, in recv_initial_metadata
    self._raise_for_grpc_status(status, message, details)
  File "/usr/local/lib/python3.11/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, "Timed out after 10.000000 seconds waiting for Device 00008030-0002292E217A402E | ICICI iPhone 11 Black | Booted | iPhone 11 | OS 'iOS 15.4' | arm64e to have an associated capture device appear", None)
2023-07-20 18:06:26,063 [ERROR] - asyncio - Task was destroyed but it is pending!
task: <Task pending name='Task-8' coro=<Event.wait() done, defined at /usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py:200> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at /usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py:754]>

```

**Comment by answer-huang** [comment]
Same problem occur on my M1 pro:

`Conversion failed!
2023-07-26 16:42:08,776 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/idb/cli/main.py", line 313, in gen_main
    await root_command.run(args)
  File "/opt/homebrew/lib/python3.11/site-packages/idb/common/command.py", line 90, in run
    return await self.resolve_command_from_args(args).run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/idb/cli/__init__.py", line 106, in run
    await self._run_impl(args)
  File "/opt/homebrew/lib/python3.11/site-packages/idb/cli/__init__.py", line 128, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "/opt/homebrew/lib/python3.11/site-packages/idb/cli/commands/video.py", line 99, in run_with_client
    sys.stdout.buffer.write(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-07-26 16:42:08,791 [ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-9015' coro=<<async_generator_athrow without __name__>()> exception=StreamTerminatedError('Connection lost')>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/idb/grpc/client.py", line 1061, in stream_video
    yield data
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/idb/grpc/client.py", line 1064, in stream_video
    await stream.send_message(
  File "/opt/homebrew/lib/python3.11/site-packages/grpclib/client.py", line 253, in send_message
    with self._wrapper:
  File "/opt/homebrew/lib/python3.11/site-packages/grpclib/utils.py", line 51, in __enter__
    raise self._error
grpclib.exceptions.StreamTerminatedError: Connection lost
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
2023-07-26 16:42:10,820 [ERROR] - asyncio - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Event.wait() done, defined at /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py:200> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py:754]>`

**Comment by rgon** [comment]
I also found the same issue on `1.1.7`. However, it's gladly fixed in `1.6.1`. The issue can be closed!
